### ISSUE TITLE
Failed to Get Synthesis Report

### ISSUE THREAD

**Issue by jasvinderkhurana** [ros-acceleration/acceleration_examples#2]
I am trying to get synthesis report for simple_adder accelerator, but it is not executing C Simulation. Please see logs below

```
jasvinder@jasvinder-ubuntu:~/krs_ws$ colcon acceleration list
kv260*
jasvinder@jasvinder-ubuntu:~/krs_ws$ colcon build  --merge-install --build-base=build-kv260 --install-base=install-kv260 --mixin kv260 --packages-select simple_adder
Starting >>> simple_adder
[0.821s] WARNING:colcon.colcon_core.shell:The following packages are in the workspace but haven't been built:
- ament_vitis
They are being used from the following locations instead:
- /home/jasvinder/krs_ws/install
To suppress this warning ignore these packages in the workspace:
--packages-ignore ament_vitis
Finished <<< simple_adder [7.97s]                     

Summary: 1 package finished [8.38s]
jasvinder@jasvinder-ubuntu:~/krs_ws$ colcon acceleration hls simple_adder
 Project:  project_simpleadder1
 Path:  /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder1
 	- Solution:  solution_4ns
 		- C Simulation:               Not Run
 		- C Synthesis:                Not Run
 		- C/RTL Co-simulation:        Not Run
		- Export:
 			- IP Catalog:         Not Run
 			- System Generator:   Not Run
 			- Export Evaluation:  Not Run
 Project:  project_simpleadder2
 Path:  /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder2
 	- Solution:  solution_4ns
 		- C Simulation:               Not Run
 		- C Synthesis:                Not Run
 		- C/RTL Co-simulation:        Not Run
		- Export:
 			- IP Catalog:         Not Run
 			- System Generator:   Not Run
 			- Export Evaluation:  Not Run
 	- Solution:  solution_10ns
 		- C Simulation:               Not Run
 		- C Synthesis:                Not Run
 		- C/RTL Co-simulation:        Not Run
		- Export:
 			- IP Catalog:         Not Run
 			- System Generator:   Not Run
 			- Export Evaluation:  Not Run
jasvinder@jasvinder-ubuntu:~/krs_ws$ colcon acceleration hls simple_adder --run
Found Tcl script "project_simpleadder1.tcl" for package: simple_adder
Executing /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder1.tcl
Found Tcl script "project_simpleadder2.tcl" for package: simple_adder
Executing /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder2.tcl
 Project:  project_simpleadder1
 Path:  /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder1
 	- Solution:  solution_4ns
 		- C Simulation:               Not Run
 		- C Synthesis:                Not Run
 		- C/RTL Co-simulation:        Not Run
		- Export:
 			- IP Catalog:         Not Run
 			- System Generator:   Not Run
 			- Export Evaluation:  Not Run
 Project:  project_simpleadder2
 Path:  /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder2
 	- Solution:  solution_4ns
 		- C Simulation:               Not Run
 		- C Synthesis:                Not Run
 		- C/RTL Co-simulation:        Not Run
		- Export:
 			- IP Catalog:         Not Run
 			- System Generator:   Not Run
 			- Export Evaluation:  Not Run
 	- Solution:  solution_10ns
 		- C Simulation:               Not Run
 		- C Synthesis:                Not Run
 		- C/RTL Co-simulation:        Not Run
		- Export:
 			- IP Catalog:         Not Run
 			- System Generator:   Not Run
 			- Export Evaluation:  Not Run
jasvinder@jasvinder-ubuntu:~/krs_ws$ colcon acceleration hls simple_adder --synthesis-report
 Project:  project_simpleadder1
 Path:  /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder1
 	- Solution:  solution_4ns
 		- C Simulation:               Not Run
 		- C Synthesis:                Not Run
 		- C/RTL Co-simulation:        Not Run
		- Export:
 			- IP Catalog:         Not Run
 			- System Generator:   Not Run
 			- Export Evaluation:  Not Run
		- Synthesis report: /home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder1/solution_4ns/syn/report/simple_adder_csynth.rpt
[0.537s] ERROR:colcon:colcon acceleration: [Errno 2] No such file or directory: '/home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder1/solution_4ns/syn/report/simple_adder_csynth.rpt'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 528, in verb_main
    rc = context.args.main(context=context)
  File "/home/jasvinder/krs_ws/install/lib/python3.8/site-packages/colcon_acceleration/subverb/hls.py", line 495, in main
    self.print_status_solution(s, configuration, context)
  File "/home/jasvinder/krs_ws/install/lib/python3.8/site-packages/colcon_acceleration/subverb/hls.py", line 273, in print_status_solution
    with open(csyn_path,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jasvinder/krs_ws/build-kv260/simple_adder/project_simpleadder1/solution_4ns/syn/report/simple_adder_csynth.rpt'

```

Please guide for possible issue.

**Comment by vmayoral** [comment]
@jasvinderkhurana what's the status of this ticket?

**Comment by vmayoral** [comment]
Closing since there's not further responses.
